spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        maximum-pool-size: 10         
        minimum-idle: 2                
        idle-timeout: 30000            # Thời gian (ms) tối đa một kết nối nhàn rỗi được giữ trước khi bị loại bỏ (30 giây)
        pool-name: MyHikariCP         
        connection-timeout: 30000      # Thời gian chờ tối đa (ms) để lấy được connection từ pool (30 giây)
        max-lifetime: 1800000          # Thời gian tối đa (ms) mà một connection có thể tồn tại trong pool (30 phút)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MY_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true     

logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG
    com:
      zaxxer:
        hikari: DEBUG

server:
  port: 8000